### ISSUE TITLE
Quiestion/suggestion: support dynamic config in container_window_v3

### ISSUE THREAD

**Issue by TheQwertiest** [reupen/columns_ui-sdk#51]
A small intro: I've tried updating my component to the latest CUI SDK and when compiling the project it complained about `container_window` deprecation. I've tried updating `container_window` with the suggested `container_window_v3`, but soon found a big compatibility problem: `container_window_v3` requires for `container_window_v3_config` to be passed during it's creation, while  `container_window` used a method, which allowed for dynamic config substitution.

Would it be possible to expose `m_config` from `container_window_v3`, so that it could be changed dynamically, thus retaining the feature parity with `container_window`?
I've checked the code of  `container_window_v3` and it doesn't seem that there are instances where the persistence of the config is actually required.

PS: TBH, the only thing I need it for is edge styles, but, if possible, I'd rather keep the feature.

**Comment by TheQwertiest** [comment]
Nvm, I think, I've figured it out =)

**Comment by reupen** [comment]
Hi,

Yes, `container_window` demanded inheritance while `container_window_v3` is meant to be used as a normal object (i.e. composed).

What `container_uie_window_v3` does (which I assume is where you ended up) is create a new `container_window` each time a window is created.

Perhaps some methods to update styles dynamically would be useful, though it is meant to be a lightweight wrapper also 🙂 

Thanks

**Comment by TheQwertiest** [comment]
> which I assume is where you ended up

yup, that's exactly what I did. It actually made my code a bit cleaner as well =)
